services:
    web:
        build: ./nextbnb_backend
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./nextbnb_backend:/usr/src/nextbnb_backend
        ports:
            - "8000:8000"
        env_file:
            - ./.env.dev
        depends_on:
            - db
        environment:
            - SQL_ENGINE=django.db.backends.postgresql
            - SQL_DATABASE=nextbnb
            - SQL_USER=postgresuser
            - SQL_PASSWORD=postgrespassword
            - SQL_HOST=db
            - SQL_PORT=5432

    db:
        image: postgres:15
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgresuser
            - POSTGRES_PASSWORD=postgrespassword
            - POSTGRES_DB=nextbnb
        ports:
            - "5432:5432"

volumes:
    postgres_data:
